/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Collaborator;
import Service.CollaboratorService;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import javax.swing.JOptionPane;


/**
 *
 * @author Guilaine
 */
public class Collaborators_frame extends javax.swing.JFrame {


    /**
     * Creates new form Staff_Frame
     */
    public Collaborators_frame() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        collaphoneTxt = new javax.swing.JTextField();
        collanameTxt = new javax.swing.JTextField();
        collaaddressTxt = new javax.swing.JTextField();
        collaregisterbtn = new javax.swing.JButton();
        collaupdatebtn = new javax.swing.JButton();
        colladeletebtn = new javax.swing.JButton();
        collaclearbtn = new javax.swing.JButton();
        collasearchbtn = new javax.swing.JButton();
        searchcollaTxt = new javax.swing.JTextField();
        retrievecollabtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        staffclicked = new javax.swing.JLabel();
        eventsclicked = new javax.swing.JLabel();
        collaboratorsclicked = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LogoutMouseClicked = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0, 120));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("COLLABORATORS MANAGEMENT");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Collaborator's address:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Collaborator's Name:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Collaborator's phone number:");

        collaphoneTxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        collaphoneTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collaphoneTxtActionPerformed(evt);
            }
        });

        collanameTxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        collanameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collanameTxtActionPerformed(evt);
            }
        });

        collaaddressTxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        collaaddressTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collaaddressTxtActionPerformed(evt);
            }
        });

        collaregisterbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        collaregisterbtn.setText("Register");
        collaregisterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collaregisterbtnActionPerformed(evt);
            }
        });

        collaupdatebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        collaupdatebtn.setText("Update");
        collaupdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collaupdatebtnActionPerformed(evt);
            }
        });

        colladeletebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        colladeletebtn.setText("Delete");
        colladeletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colladeletebtnActionPerformed(evt);
            }
        });

        collaclearbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        collaclearbtn.setText("Clear");
        collaclearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collaclearbtnActionPerformed(evt);
            }
        });

        collasearchbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        collasearchbtn.setText("Search");
        collasearchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collasearchbtnActionPerformed(evt);
            }
        });

        searchcollaTxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        retrievecollabtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        retrievecollabtn.setText("Retrieve Collaborators");
        retrievecollabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrievecollabtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(231, 231, 231))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(searchcollaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(collasearchbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(collaupdatebtn)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(collanameTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(collaaddressTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(collaphoneTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addGap(35, 35, 35)
                .addComponent(colladeletebtn)
                .addGap(132, 132, 132))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(collaregisterbtn)
                .addGap(67, 67, 67)
                .addComponent(retrievecollabtn)
                .addGap(71, 71, 71)
                .addComponent(collaclearbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(85, 85, 85)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchcollaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(collasearchbtn)
                    .addComponent(collaupdatebtn)
                    .addComponent(colladeletebtn))
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(collanameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(collaaddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(collaphoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(collaregisterbtn)
                    .addComponent(retrievecollabtn)
                    .addComponent(collaclearbtn))
                .addGap(121, 121, 121))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 890, 610));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 170));

        staffclicked.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        staffclicked.setForeground(new java.awt.Color(240, 240, 240));
        staffclicked.setText("Manage Staff");
        staffclicked.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffclickedMouseClicked(evt);
            }
        });

        eventsclicked.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        eventsclicked.setForeground(new java.awt.Color(240, 240, 240));
        eventsclicked.setText("Manage Events");
        eventsclicked.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventsclickedMouseClicked(evt);
            }
        });

        collaboratorsclicked.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        collaboratorsclicked.setForeground(new java.awt.Color(240, 240, 240));
        collaboratorsclicked.setText("Manage Collaborators");
        collaboratorsclicked.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                collaboratorsclickedMouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Guilaine\\Pictures\\Bk Arena\\Bk arena.jpg")); // NOI18N

        LogoutMouseClicked.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LogoutMouseClicked.setForeground(new java.awt.Color(240, 240, 240));
        LogoutMouseClicked.setText("LogOut");
        LogoutMouseClicked.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClickedMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(collaboratorsclicked))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eventsclicked)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(staffclicked)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(LogoutMouseClicked)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staffclicked)
                .addGap(18, 18, 18)
                .addComponent(eventsclicked)
                .addGap(18, 18, 18)
                .addComponent(collaboratorsclicked)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LogoutMouseClicked)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 280, 610));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Guilaine\\Pictures\\Arena enough size\\pexels-divyesh-maheshwari-3661650     1.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void staffclickedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffclickedMouseClicked
        // TODO add your handling code here:
        Staff_Frame staff=new Staff_Frame();
        staff.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_staffclickedMouseClicked

    private void eventsclickedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventsclickedMouseClicked
        // TODO add your handling code here:
        Events_Frame event=new Events_Frame();
        event.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_eventsclickedMouseClicked

    private void collaboratorsclickedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_collaboratorsclickedMouseClicked
        // TODO add your handling code here:
        Collaborators_frame colla=new Collaborators_frame();
        colla.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_collaboratorsclickedMouseClicked

    private void collaaddressTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collaaddressTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_collaaddressTxtActionPerformed

    private void collaphoneTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collaphoneTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_collaphoneTxtActionPerformed

    private void collaupdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collaupdatebtnActionPerformed
        // TODO add your handling code here:
       // Validations
      // 1. ID mandatory
if (searchcollaTxt.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "ID is mandatory!", "Mandatory field", JOptionPane.WARNING_MESSAGE);
}else if(collaphoneTxt.getText().trim().length() !=10){
        JOptionPane.showMessageDialog(this, "Phone number should be exactly 13 characters", "Invalid Input", JOptionPane.WARNING_MESSAGE);
    }else {    
                try {
                    Registry theregistry = LocateRegistry.getRegistry("127.0.0.1" ,5000);
                    CollaboratorService service=(CollaboratorService)theregistry.lookup("col");
                Collaborator thecolla=new Collaborator();
                thecolla.setCo_id(Integer.parseInt(searchcollaTxt.getText()));
                thecolla.setCo_name(collanameTxt.getText());
                thecolla.setCo_address(collaaddressTxt.getText());
                thecolla.setCo_contact(collaphoneTxt.getText());
                    Collaborator colobj=service.modifyCollaborator(thecolla);
                if(colobj!=null){
                    JOptionPane.showMessageDialog(this, "Collaborator Updated successfully!");
                }else{
                    JOptionPane.showMessageDialog(this, "Collaborator not Updated! Try again.");
                }
    } catch (Exception ex) {
        ex.printStackTrace();
    }
        }    
    }//GEN-LAST:event_collaupdatebtnActionPerformed

    private void collaregisterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collaregisterbtnActionPerformed
        // TODO add your handling code here:
        //validations
        //1.Mandatory fields
      if (collanameTxt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Collaboratr's Name is mandatory!", "Mandatory field", JOptionPane.WARNING_MESSAGE);
    } else if (collaaddressTxt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Collaborator's Address is mandatory!", "Mandatory field", JOptionPane.WARNING_MESSAGE);
    }else if (collaphoneTxt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Collaborator's phone Number is mandatory!", "Mandatory field", JOptionPane.WARNING_MESSAGE);
    }else if(collaphoneTxt.getText().trim().length() !=10){
        JOptionPane.showMessageDialog(this, "Phone number should be exactly 10 characters", "Invalid Input", JOptionPane.WARNING_MESSAGE);
    }  
         else {
            try {
                    Registry theregistry = LocateRegistry.getRegistry("127.0.0.1" ,5000);
                    CollaboratorService service=(CollaboratorService)theregistry.lookup("col");
                Collaborator thecolla=new Collaborator();
                //theEvent.setEv_id(Integer.parseInt(searcheventTxt.getText()));
                thecolla.setCo_name(collanameTxt.getText());
                thecolla.setCo_address(collaaddressTxt.getText());
                thecolla.setCo_contact(collaphoneTxt.getText());
                    Collaborator colobj=service.recordCollaborator(thecolla);
                if(colobj!=null){
                    JOptionPane.showMessageDialog(this, "Collaborator Registered!");
                }else{
                    JOptionPane.showMessageDialog(this, "Collaborator not Registered! Try again.");
                }
    } catch (Exception ex) {
        ex.printStackTrace();
    }
    }
            
    }//GEN-LAST:event_collaregisterbtnActionPerformed

    private void collaclearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collaclearbtnActionPerformed
        // TODO add your handling code here:
        collanameTxt.setEditable(true);
        collaaddressTxt.setEditable(true);
        collaphoneTxt.setEditable(true);
        searchcollaTxt.setEditable(true);

    collanameTxt.setText("");
    collaaddressTxt.setText("");
    collaphoneTxt.setText("");
    searchcollaTxt.setText("");
   
    }//GEN-LAST:event_collaclearbtnActionPerformed

    private void colladeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colladeletebtnActionPerformed
     if (searchcollaTxt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "ID is mandatory!", "Mandatory field", JOptionPane.WARNING_MESSAGE);
    } else {
        try {
                Registry theregistry = LocateRegistry.getRegistry("127.0.0.1" ,5000);
                CollaboratorService service=(CollaboratorService)theregistry.lookup("col");
                Collaborator thecolla=new Collaborator();
                thecolla.setCo_id(Integer.parseInt(searchcollaTxt.getText()));
                Collaborator colobj=service.removeCollaborator(thecolla);
             if (colobj!=null) {
            
            collanameTxt.setEditable(false);
            collaaddressTxt.setEditable(false);
            collaphoneTxt.setEditable(false);
                JOptionPane.showMessageDialog(this, "Collaborator's information deleted successfully!", "Deletion Successful", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Collaborator's information not deleted", "Deletion Failed", JOptionPane.ERROR_MESSAGE);
            }
            } catch (Exception ex) {
                    ex.printStackTrace();            
            }
    }                   
    
    }//GEN-LAST:event_colladeletebtnActionPerformed

    private void collasearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collasearchbtnActionPerformed
        // TODO add your handling code here:
     if (searchcollaTxt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "ID is mandatory!", "Mandatory field", JOptionPane.WARNING_MESSAGE);
    } else {
        try {
                Registry theregistry = LocateRegistry.getRegistry("127.0.0.1" ,5000);
                CollaboratorService service=(CollaboratorService)theregistry.lookup("col");
                Collaborator thecolla=new Collaborator();
                thecolla.setCo_id(Integer.parseInt(searchcollaTxt.getText()));
                //thestaff.setStaffid(searchidtxt.getText());
                Collaborator colobj=service.findidCollaborator(thecolla);
                if (colobj!=null){
                    collanameTxt.setText(colobj.getCo_name());
                    collaaddressTxt.setText(colobj.getCo_address());
                collaphoneTxt.setText(colobj.getCo_contact());
            //combostaff.setSelectedItem(stobj.getDepartments());
            collanameTxt.setEditable(false);
            collaaddressTxt.setEditable(false);
            collaphoneTxt.setEditable(false);
                }else{
                collanameTxt.setText("");
                collaaddressTxt.setText("");
                collaphoneTxt.setText("");
                JOptionPane.showMessageDialog(this, "Collaborator not found");
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }   
    }     
    }//GEN-LAST:event_collasearchbtnActionPerformed

    private void collanameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collanameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_collanameTxtActionPerformed

    private void LogoutMouseClickedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClickedMouseClicked
        // TODO add your handling code here:
            int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout", JOptionPane.YES_NO_OPTION);
    if (choice == JOptionPane.YES_OPTION) {
        Login loginFrame = new Login();
        loginFrame.setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_LogoutMouseClickedMouseClicked

    private void retrievecollabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrievecollabtnActionPerformed
        // TODO add your handling code here:
        RetrieveColla_Frame colla=new RetrieveColla_Frame();
        colla.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_retrievecollabtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Collaborators_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Collaborators_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Collaborators_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Collaborators_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Collaborators_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoutMouseClicked;
    private javax.swing.JTextField collaaddressTxt;
    private javax.swing.JLabel collaboratorsclicked;
    private javax.swing.JButton collaclearbtn;
    private javax.swing.JButton colladeletebtn;
    private javax.swing.JTextField collanameTxt;
    private javax.swing.JTextField collaphoneTxt;
    private javax.swing.JButton collaregisterbtn;
    private javax.swing.JButton collasearchbtn;
    private javax.swing.JButton collaupdatebtn;
    private javax.swing.JLabel eventsclicked;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton retrievecollabtn;
    private javax.swing.JTextField searchcollaTxt;
    private javax.swing.JLabel staffclicked;
    // End of variables declaration//GEN-END:variables
}
