/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Event;
import Model.EventType;
import Service.EventService;
import Service.EventTypeService;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;




/**
 *
 * @author Guilaine
 */
public class Events_Frame extends javax.swing.JFrame {
   private JTable table;
    private Timer timer;
    /**
     * Creates new form Staff_Frame
     */
    public Events_Frame() {
        initComponents();
        addComboItem();
    }
        private void addComboItem(){
        try {
            Registry theRegistry = LocateRegistry.getRegistry("127.0.0.1" ,5000);
            EventTypeService service=(EventTypeService) theRegistry.lookup("evt");
            List<EventType> evetypes=service.EventTypeall();
            EventType selecteventtype = new EventType();
            selecteventtype.setType_name("Select");
            eventtypecombo.addItem(selecteventtype);
            for (EventType theevty : evetypes){
                eventtypecombo.addItem(theevty); 
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        eventnoTxt = new javax.swing.JTextField();
        eventnameTxt = new javax.swing.JTextField();
        eventregisterbtn = new javax.swing.JButton();
        eventupdatebtn = new javax.swing.JButton();
        eventdeletebtn = new javax.swing.JButton();
        eventclearbtn = new javax.swing.JButton();
        eventsearchbtn = new javax.swing.JButton();
        eventdateTXt = new javax.swing.JFormattedTextField();
        eventtypecombo = new javax.swing.JComboBox<>();
        RetrieveEventbtn = new javax.swing.JButton();
        searcheventTxt = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        staffclicked = new javax.swing.JLabel();
        eventsclicked = new javax.swing.JLabel();
        collaboratorsclicked = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LogoutMouseClicked = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0, 120));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("EVENT MANAGEMENT");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Event no:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Event Date:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Event Type:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Event Name:");

        eventnoTxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        eventnameTxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        eventregisterbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        eventregisterbtn.setText("Register");
        eventregisterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventregisterbtnActionPerformed(evt);
            }
        });

        eventupdatebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        eventupdatebtn.setText("Update");
        eventupdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventupdatebtnActionPerformed(evt);
            }
        });

        eventdeletebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        eventdeletebtn.setText("Delete");
        eventdeletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventdeletebtnActionPerformed(evt);
            }
        });

        eventclearbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        eventclearbtn.setText("Clear");
        eventclearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventclearbtnActionPerformed(evt);
            }
        });

        eventsearchbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        eventsearchbtn.setText("Search");
        eventsearchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventsearchbtnActionPerformed(evt);
            }
        });

        eventdateTXt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/mm/yyyy"))));
        eventdateTXt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        eventtypecombo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        RetrieveEventbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RetrieveEventbtn.setText("Retrieve all Events");
        RetrieveEventbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetrieveEventbtnActionPerformed(evt);
            }
        });

        searcheventTxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(140, 140, 140)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(eventclearbtn))
                                    .addComponent(eventtypecombo, 0, 236, Short.MAX_VALUE))
                                .addGap(207, 207, 207))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eventnoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eventnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eventdateTXt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(90, 90, 90))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(eventregisterbtn)
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RetrieveEventbtn)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(searcheventTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(eventsearchbtn)
                        .addGap(31, 31, 31)
                        .addComponent(eventdeletebtn)
                        .addGap(45, 45, 45)
                        .addComponent(eventupdatebtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searcheventTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eventsearchbtn)
                    .addComponent(eventdeletebtn)
                    .addComponent(eventupdatebtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventnoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventdateTXt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(eventtypecombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventregisterbtn)
                    .addComponent(RetrieveEventbtn)
                    .addComponent(eventclearbtn))
                .addGap(143, 143, 143))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 890, 690));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 170));

        staffclicked.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        staffclicked.setForeground(new java.awt.Color(240, 240, 240));
        staffclicked.setText("Manage Staff");
        staffclicked.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffclickedMouseClicked(evt);
            }
        });

        eventsclicked.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        eventsclicked.setForeground(new java.awt.Color(240, 240, 240));
        eventsclicked.setText("Manage Events");
        eventsclicked.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventsclickedMouseClicked(evt);
            }
        });

        collaboratorsclicked.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        collaboratorsclicked.setForeground(new java.awt.Color(240, 240, 240));
        collaboratorsclicked.setText("Manage Collaborators");
        collaboratorsclicked.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                collaboratorsclickedMouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Guilaine\\Pictures\\Bk Arena\\Bk arena.jpg")); // NOI18N

        LogoutMouseClicked.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LogoutMouseClicked.setForeground(new java.awt.Color(240, 240, 240));
        LogoutMouseClicked.setText("LogOut");
        LogoutMouseClicked.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClickedMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(collaboratorsclicked))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eventsclicked)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(staffclicked)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(LogoutMouseClicked)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staffclicked)
                .addGap(18, 18, 18)
                .addComponent(eventsclicked)
                .addGap(18, 18, 18)
                .addComponent(collaboratorsclicked)
                .addGap(18, 18, 18)
                .addComponent(LogoutMouseClicked)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 280, 690));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Guilaine\\Pictures\\Arena enough size\\pexels-ludvig-hedenborg-18447992  111.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void staffclickedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffclickedMouseClicked
        // TODO add your handling code here:
        Staff_Frame staff=new Staff_Frame();
        staff.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_staffclickedMouseClicked

    private void eventsclickedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventsclickedMouseClicked
        // TODO add your handling code here:
        Events_Frame event=new Events_Frame();
        event.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_eventsclickedMouseClicked

    private void collaboratorsclickedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_collaboratorsclickedMouseClicked
        // TODO add your handling code here:
        Collaborators_frame colla=new Collaborators_frame();
        colla.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_collaboratorsclickedMouseClicked

    private void eventupdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventupdatebtnActionPerformed
        // TODO add your handling code here:
       // Validations
// 1. ID mandatory
if (eventnoTxt.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Event ID is mandatory!", "Mandatory field", JOptionPane.WARNING_MESSAGE);
} else if (eventnoTxt.getText().trim().length() != 3) {
    JOptionPane.showMessageDialog(this, "Event ID must be exactly 3 characters long!", "Invalid input", JOptionPane.ERROR_MESSAGE);
} else {
                try {
                    Registry theregistry = LocateRegistry.getRegistry("127.0.0.1" ,5000);
                    EventService service=(EventService)theregistry.lookup("ev");
                Event theEvent=new Event();
                theEvent.setEv_id(Integer.parseInt(searcheventTxt.getText()));
                theEvent.setEventno(eventnoTxt.getText());
                theEvent.setEvent_name(eventnameTxt.getText());
                Date selectedDate = (Date) eventdateTXt.getValue(); 
                theEvent.setEvent_date((selectedDate));
                EventType selectedevety=(EventType)eventtypecombo.getSelectedItem();
                theEvent.setEventType(selectedevety);
                    Event evobj=service.modifyEvent(theEvent);
                if(evobj!=null){
                    JOptionPane.showMessageDialog(this, "Event Updated!");
                }else{
                    JOptionPane.showMessageDialog(this, "Event not Updated! Try again.");
                }
    } catch (Exception ex) {
        ex.printStackTrace();
    }
}

    
    }//GEN-LAST:event_eventupdatebtnActionPerformed

    private void eventregisterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventregisterbtnActionPerformed
        // TODO add your handling code here:
        //validations
        //1.Mandatory fields
        if (eventnoTxt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "ID is mandatory!", "Mandatory field", JOptionPane.WARNING_MESSAGE);
    } else if (eventnameTxt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Event Name is mandatory!", "Mandatory field", JOptionPane.WARNING_MESSAGE);
    }  else if (eventdateTXt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Event Date is mandatory!", "Mandatory field", JOptionPane.WARNING_MESSAGE);
    }else if ("Select".equals(eventtypecombo.getSelectedItem())) {
        JOptionPane.showMessageDialog(this, "Select the event type to continue!", "Mandatory Field", JOptionPane.WARNING_MESSAGE);
    }  else if (eventnoTxt.getText().trim().length() != 3) {
        JOptionPane.showMessageDialog(this, "Staff ID must be exactly 3 characters long!", "Invalid input", JOptionPane.ERROR_MESSAGE);
    }else{          
                try {
                    Registry theregistry = LocateRegistry.getRegistry("127.0.0.1" ,5000);
                    EventService service=(EventService)theregistry.lookup("ev");
                Event theEvent=new Event();
                //theEvent.setEv_id(Integer.parseInt(searcheventTxt.getText()));
                theEvent.setEventno(eventnoTxt.getText());
                theEvent.setEvent_name(eventnameTxt.getText());
                Date selectedDate = (Date) eventdateTXt.getValue(); 
                theEvent.setEvent_date((selectedDate));
                EventType selectedevety=(EventType)eventtypecombo.getSelectedItem();
                theEvent.setEventType(selectedevety);
                if ("Select".equals(selectedevety.getType_name())) {
    JOptionPane.showMessageDialog(this, "Select Event Type to continue!", "Mandatory Field", JOptionPane.WARNING_MESSAGE);
}
                    Event evobj=service.recordEvent(theEvent);
                if(evobj!=null){
                    JOptionPane.showMessageDialog(this, "Event Registered!");
                }else{
                    JOptionPane.showMessageDialog(this, "Event not Registered! Try again.");
                }
    } catch (Exception ex) {
        ex.printStackTrace();
    }
            }
    }//GEN-LAST:event_eventregisterbtnActionPerformed

    private void eventclearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventclearbtnActionPerformed
        // TODO add your handling code here:
        eventnameTxt.setEditable(true);
        eventnoTxt.setEditable(true);
        eventdateTXt.setEditable(true);
        searcheventTxt.setEditable(true);
        eventtypecombo.setEditable(true);
    eventnoTxt.setText("");
    eventnameTxt.setText("");
    eventdateTXt.setText("");
    searcheventTxt.setText("");
    eventtypecombo.setSelectedIndex(0);
    }//GEN-LAST:event_eventclearbtnActionPerformed

    private void eventdeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventdeletebtnActionPerformed
        // TODO add your handling code here:
        if (searcheventTxt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Event ID is mandatory!", "Mandatory field", JOptionPane.WARNING_MESSAGE);
    }  else {
        try {
                Registry theregistry = LocateRegistry.getRegistry("127.0.0.1" ,5000);
                EventService service=(EventService)theregistry.lookup("ev");
                Event theEvent=new Event();
                theEvent.setEv_id(Integer.parseInt(searcheventTxt.getText()));
                Event evobj=service.removeEvent(theEvent);
             if (evobj!=null) {
            
            eventtypecombo.setEditable(false);
            eventnoTxt.setEditable(false);
            eventdateTXt.setEditable(false);
            eventnameTxt.setEditable(false);
                JOptionPane.showMessageDialog(this, "Event's information deleted successfully!", "Deletion Successful", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Event's information not deleted", "Deletion Failed", JOptionPane.ERROR_MESSAGE);
            }
            } catch (Exception ex) {
                    ex.printStackTrace();            
            }
    }                   
    }//GEN-LAST:event_eventdeletebtnActionPerformed

    private void eventsearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventsearchbtnActionPerformed
        // TODO add your handling code here:
              if (searcheventTxt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "ID is mandatory!", "Mandatory field", JOptionPane.WARNING_MESSAGE);
    }  else {
        try {
                Registry theregistry = LocateRegistry.getRegistry("127.0.0.1" ,5000);
                EventService service=(EventService)theregistry.lookup("ev");
                Event theEvent=new Event();
                theEvent.setEv_id(Integer.parseInt(searcheventTxt.getText()));
                //thestaff.setStaffid(searchidtxt.getText());
                Event evobj=service.findidEvent(theEvent);
                if (evobj!=null){
                    eventnoTxt.setText(evobj.getEventno());
                    eventnameTxt.setText(evobj.getEvent_name());
                eventdateTXt.setValue(evobj.getEvent_date());
                EventType eventtype = evobj.getEventType();
                if (eventtype != null) {
        eventtypecombo.setSelectedItem(eventtype);
    } else {
        eventtypecombo.setSelectedIndex(-1);
    }
            //combostaff.setSelectedItem(stobj.getDepartments());
            eventtypecombo.setEditable(false);
            eventnoTxt.setEditable(false);
            eventdateTXt.setEditable(false);
            eventnameTxt.setEditable(false);
                }else{
                eventnameTxt.setText("");
                eventnoTxt.setText("");
                eventdateTXt.setText("");
                eventtypecombo.setSelectedIndex(-1);
                JOptionPane.showMessageDialog(this, "Event not found");
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }           
            
    }     
    }//GEN-LAST:event_eventsearchbtnActionPerformed

    private void LogoutMouseClickedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClickedMouseClicked
        // TODO add your handling code here:
            int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout", JOptionPane.YES_NO_OPTION);
    if (choice == JOptionPane.YES_OPTION) {
        Login loginFrame = new Login();
        loginFrame.setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_LogoutMouseClickedMouseClicked

    private void RetrieveEventbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetrieveEventbtnActionPerformed
        // TODO add your handling code here:
        RetrieveEvent_Frame ret=new RetrieveEvent_Frame();
        ret.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RetrieveEventbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Events_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Events_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Events_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Events_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Events_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoutMouseClicked;
    private javax.swing.JButton RetrieveEventbtn;
    private javax.swing.JLabel collaboratorsclicked;
    private javax.swing.JButton eventclearbtn;
    private javax.swing.JFormattedTextField eventdateTXt;
    private javax.swing.JButton eventdeletebtn;
    private javax.swing.JTextField eventnameTxt;
    private javax.swing.JTextField eventnoTxt;
    private javax.swing.JButton eventregisterbtn;
    private javax.swing.JLabel eventsclicked;
    private javax.swing.JButton eventsearchbtn;
    private javax.swing.JComboBox<EventType> eventtypecombo;
    private javax.swing.JButton eventupdatebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField searcheventTxt;
    private javax.swing.JLabel staffclicked;
    // End of variables declaration//GEN-END:variables
}
