/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Collaborator;
import Model.Event;
import Model.EventType;
import Service.CollaboratorService;
import java.util.logging.Level;
import java.util.logging.Logger;
import Service.EventService;
import Service.EventTypeService;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.io.IOException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Guilaine
 */
public class RetrieveColla_Frame extends javax.swing.JFrame {

    /**
     * Creates new form retrievestaff
     */
    private DefaultTableModel tablemodel=new DefaultTableModel();
    public RetrieveColla_Frame() {
        initComponents();
        addstafftable();
        addtabledata();
        printbtn.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        printbtnActionPerformed(evt);
    }
});

    }
    private void exporttoPdf(){
        try {
        Document document=new Document();
        PdfWriter.getInstance(document, new FileOutputStream("CollaboratorData.pdf"));
        document.open();
        PdfPTable pdfTable = new PdfPTable(tablemodel.getColumnCount());
        for (int i = 0; i < tablemodel.getColumnCount(); i++) {
            pdfTable.addCell(new PdfPCell(new Phrase(tablemodel.getColumnName(i))));
        }
        for (int i = 0; i < tablemodel.getRowCount(); i++) {
            for (int j = 0; j < tablemodel.getColumnCount(); j++) {
                pdfTable.addCell(new PdfPCell(new Phrase(String.valueOf(tablemodel.getValueAt(i, j)))));
            }
        }
        document.add(pdfTable);
        document.close();
         } catch (DocumentException | IOException ex) {
        Logger.getLogger(RetrieveColla_Frame.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    
    private void addstafftable(){
        tablemodel.addColumn("Collaborator name");
        tablemodel.addColumn("Collaborator Address");
        tablemodel.addColumn("Collaborator Contact");
        CollaTable.setModel(tablemodel);
    }
    private void addtabledata(){
        try {
            Registry theregistry = LocateRegistry.getRegistry("127.0.0.1" ,5000);
            CollaboratorService service=(CollaboratorService)theregistry.lookup("col");
            List<Collaborator> Collalist= service.Collaboratorall();
            Iterator iterator= Collalist.iterator();
            while(iterator.hasNext()){
                Collaborator col=(Collaborator)iterator.next();
                //Department dep=departservice.findstaffDepartment(depart);
                tablemodel.addRow(new Object[]{
                col.getCo_name(),
                col.getCo_address(),
                col.getCo_contact(),
                });
                CollaTable.setModel(tablemodel);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CollaTable = new javax.swing.JTable();
        printbtn = new javax.swing.JButton();
        retrievebackbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("ALL COLLABORATORS");

        CollaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(CollaTable);

        printbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        printbtn.setText("Save");
        printbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbtnActionPerformed(evt);
            }
        });

        retrievebackbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        retrievebackbtn.setText("Back");
        retrievebackbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrievebackbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(printbtn)
                        .addGap(93, 93, 93)
                        .addComponent(retrievebackbtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printbtn)
                    .addComponent(retrievebackbtn))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 850, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Guilaine\\Downloads\\pexels-francesco-ungaro-998641.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retrievebackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrievebackbtnActionPerformed
        // TODO add your handling code here:
        Collaborators_frame stf=new Collaborators_frame();
        stf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_retrievebackbtnActionPerformed

    private void printbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbtnActionPerformed
        // TODO add your handling code here:
        exporttoPdf();
        JOptionPane.showMessageDialog(this,"Document saved!", "Document Saving", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_printbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RetrieveColla_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RetrieveColla_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RetrieveColla_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RetrieveColla_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RetrieveColla_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CollaTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton printbtn;
    private javax.swing.JButton retrievebackbtn;
    // End of variables declaration//GEN-END:variables
}
