/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Accounts;
import Model.Department;
import Service.AccountService;
import Service.DepartmentService;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Guilaine
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        addComboItem();
    }
    private void addComboItem(){
        try {
            Registry theRegistry = LocateRegistry.getRegistry("127.0.0.1" ,5000);
            DepartmentService service=(DepartmentService) theRegistry.lookup("dep");
            List<Department> departs=service.Departmentall();
            Department selectDepartment = new Department();
        selectDepartment.setDep_name("Select");
        comboboxSignup.addItem(selectDepartment);
            for (Department thedepart : departs){
                comboboxSignup.addItem(thedepart); 
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Usernametxtsignup = new javax.swing.JTextField();
        comboboxSignup = new javax.swing.JComboBox<>();
        cancelbtnsignup = new javax.swing.JButton();
        signuplabelclicked = new javax.swing.JLabel();
        signupbtn = new javax.swing.JButton();
        passwordsignupTxt = new javax.swing.JPasswordField();
        reenterpasswordTxt = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,80));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("SignUp");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Enter Username:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Choose your Department:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Re-Enter password:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Create password:");

        Usernametxtsignup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Usernametxtsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernametxtsignupActionPerformed(evt);
            }
        });

        comboboxSignup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        comboboxSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxSignupActionPerformed(evt);
            }
        });

        cancelbtnsignup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancelbtnsignup.setText("Cancel");
        cancelbtnsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnsignupActionPerformed(evt);
            }
        });

        signuplabelclicked.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        signuplabelclicked.setForeground(new java.awt.Color(240, 240, 240));
        signuplabelclicked.setText("<html><u>Already have an account?Click Here to Login!</u></html>");
        signuplabelclicked.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signuplabelclickedMouseClicked(evt);
            }
        });

        signupbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        signupbtn.setText("SignUp");
        signupbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbtnActionPerformed(evt);
            }
        });

        passwordsignupTxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        reenterpasswordTxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(82, 82, 82))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordsignupTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Usernametxtsignup, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(reenterpasswordTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(comboboxSignup, javax.swing.GroupLayout.Alignment.LEADING, 0, 251, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(signupbtn)
                        .addGap(38, 38, 38)
                        .addComponent(cancelbtnsignup))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(signuplabelclicked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Usernametxtsignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboboxSignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordsignupTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reenterpasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signupbtn)
                    .addComponent(cancelbtnsignup))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signuplabelclicked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 790, 490));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Guilaine\\Pictures\\Arena enough size\\pexels-jack-gittoes-761543   2.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboboxSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxSignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxSignupActionPerformed

    private void signuplabelclickedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signuplabelclickedMouseClicked
        // TODO add your handling code here:
    Login log=new Login();
    log.setVisible(true);
    this.dispose();
            
    }//GEN-LAST:event_signuplabelclickedMouseClicked

    private void UsernametxtsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernametxtsignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernametxtsignupActionPerformed

    private void cancelbtnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnsignupActionPerformed
        // TODO add your handling code here:
        int userChoice = JOptionPane.showConfirmDialog(null, "Are you sure you want to cancel?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (userChoice == JOptionPane.YES_OPTION) {          
            this.dispose();
        } else {

        }
    }//GEN-LAST:event_cancelbtnsignupActionPerformed

    private void signupbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbtnActionPerformed
        // TODO add your handling code here:
        //validations
        //1.mandatory fields
        if(Usernametxtsignup.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Staff Id is required!","Mandatory Field",JOptionPane.WARNING_MESSAGE );
        }else if (new String(passwordsignupTxt.getPassword()).trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Password required!","Mandatory Field",JOptionPane.WARNING_MESSAGE );
        }else if (new String(reenterpasswordTxt.getPassword()).trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Re-enter your password to confirm","Mandatory Field",JOptionPane.WARNING_MESSAGE );
           //2.check if the passwords match
        }else if (!Arrays.equals(passwordsignupTxt.getPassword(), reenterpasswordTxt.getPassword()))  {
    JOptionPane.showMessageDialog(this, "Passwords do not match!", "Invalid Password", JOptionPane.WARNING_MESSAGE);
        }
         //3.password less than 6 characters
        else if(new String(passwordsignupTxt.getPassword()).trim().length() < 6) {
            JOptionPane.showMessageDialog(this, "Password must be at least 6 characters long!", "Invalid Password", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                Registry theregistry = LocateRegistry.getRegistry("127.0.0.1" ,5000);
                AccountService service=(AccountService)theregistry.lookup("acc");
                Accounts theaccount=new Accounts();
                theaccount.setStaff_id(Usernametxtsignup.getText());
                theaccount.setPassword(new String(passwordsignupTxt.getPassword()));
                Department selectedDepart=(Department) comboboxSignup.getSelectedItem();
                theaccount.setDepartment(selectedDepart);
                if ("Select".equals(comboboxSignup.getSelectedItem())) {
    JOptionPane.showMessageDialog(this, "Select your department to continue!", "Mandatory Field", JOptionPane.WARNING_MESSAGE);
    }
                Accounts accobj=service.recordAccounts(theaccount);
                if(accobj!=null){
                    JOptionPane.showMessageDialog(this, "Account created!");
                }else{
                    JOptionPane.showMessageDialog(this, "Account not created! Try again.");
                }
            Login l=new Login();
            l.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
            }
        }
                
    }//GEN-LAST:event_signupbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Usernametxtsignup;
    private javax.swing.JButton cancelbtnsignup;
    private javax.swing.JComboBox<Department> comboboxSignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passwordsignupTxt;
    private javax.swing.JPasswordField reenterpasswordTxt;
    private javax.swing.JButton signupbtn;
    private javax.swing.JLabel signuplabelclicked;
    // End of variables declaration//GEN-END:variables
}
